spring.application.name=tarefas-app

spring.datasource.url=jdbc:postgresql://nozomi.proxy.rlwy.net:51068/railway
spring.datasource.username=postgres
spring.datasource.password=RapWhjgOcKoQEaZWNZSYoffcxbkMwAyK
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}